// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"database/sql"
	"github.com/GorbachR/todo-app/api/controller"
	"github.com/GorbachR/todo-app/api/repository"
	"github.com/GorbachR/todo-app/api/service"
)

// Injectors from wire.go:

func InitTodoController(db *sql.DB) controller.TodoController {
	todoRepository := repository.CreateTodoRepository(db)
	todoService := service.CreateTodoService(todoRepository)
	todoController := controller.CreateTodoController(todoService)
	return todoController
}
