spring:
  datasource:
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: ${DLL_AUTO}
  sql:
    init:
      platform: mysql
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
server:
  port: 9000
