#DEV ONLY
version: "3.8"

services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: dev
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
